using Spectre.Console;

namespace Greg.Xrm.Command.Commands.Completion
{
	public class PowerShellCommandExecutor(
		IAnsiConsole ansiConsole
		) : ICommandExecutor<PowerShellCommand>
	{
		public Task<CommandResult> ExecuteAsync(PowerShellCommand command, CancellationToken cancellationToken)
		{
			// written through the raw output writer on purpose: the ansi console
			// renderer would hard-wrap long lines at the console width, which
			// breaks the generated script
			ansiConsole.Profile.Out.Writer.WriteLine(Script);
			return Task.FromResult(CommandResult.Success());
		}


		/// <summary>
		/// The completion script is static on purpose: it loads the command tree
		/// via "pacx completion export" on the first TAB press and caches it for
		/// the session, so it always matches the installed pacx version.
		/// </summary>
		private const string Script = """
		# pacx tab-completion for PowerShell.
		# Generated by "pacx completion powershell". Run "pacx completion powershell --help" for setup instructions.

		$global:PacxCompletionCache = $null

		Register-ArgumentCompleter -Native -CommandName pacx -ScriptBlock {
			param($wordToComplete, $commandAst, $cursorPosition)

			# Load the command tree once per session, on the first TAB press.
			if ($null -eq $global:PacxCompletionCache) {
				try {
					$raw = (pacx completion export --nologo 2>$null) -join "`n"
					$start = $raw.IndexOf('{')
					$end = $raw.LastIndexOf('}')
					if ($start -lt 0 -or $end -le $start) { return }
					$global:PacxCompletionCache = $raw.Substring($start, $end - $start + 1) | ConvertFrom-Json
				}
				catch { return }
			}
			$data = $global:PacxCompletionCache
			if ($null -eq $data) { return }

			# All tokens typed after "pacx", excluding the token being completed right now.
			$tokens = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.Extent.Text })
			if ($wordToComplete -and $tokens.Count -gt 0) {
				$tokens = @($tokens | Select-Object -First ($tokens.Count - 1))
			}

			# Split into verbs (before the first option) and options already used.
			$verbs = New-Object System.Collections.Generic.List[string]
			$usedOptions = New-Object System.Collections.Generic.List[string]
			$optionsStarted = $false
			foreach ($t in $tokens) {
				if ($t.StartsWith("-")) {
					$optionsStarted = $true
					[void]$usedOptions.Add($t)
				}
				elseif (-not $optionsStarted) {
					[void]$verbs.Add($t)
				}
			}

			# Find the command that exactly matches the typed verbs (including aliases).
			$command = $null
			foreach ($c in $data.commands) {
				$verbSets = @()
				$verbSets += , @($c.verbs)
				foreach ($a in @($c.aliases)) { if ($null -ne $a) { $verbSets += , @($a) } }
				foreach ($set in $verbSets) {
					if ($set.Count -ne $verbs.Count) { continue }
					$isMatch = $true
					for ($i = 0; $i -lt $set.Count; $i++) {
						if ($set[$i] -ne $verbs[$i]) { $isMatch = $false; break }
					}
					if ($isMatch) { $command = $c; break }
				}
				if ($null -ne $command) { break }
			}

			$results = @()

			if ($null -ne $command) {
				# If the previous token is an option with a fixed set of values, complete those.
				if ($tokens.Count -gt 0) {
					$prev = $tokens[$tokens.Count - 1]
					if ($prev.StartsWith("-")) {
						foreach ($o in @($command.options)) {
							$isPrev = ("--" + $o.long) -eq $prev
							if (-not $isPrev -and $o.short) { $isPrev = ("-" + $o.short) -eq $prev }
							if ($isPrev -and $o.values) {
								foreach ($v in @($o.values)) {
									if ($v -like "$wordToComplete*") {
										$results += [System.Management.Automation.CompletionResult]::new($v, $v, "ParameterValue", $v)
									}
								}
								break
							}
						}
						if ($results.Count -gt 0) { return $results }
					}
				}

				# Otherwise complete the options of the command that were not used yet.
				foreach ($o in @($command.options)) {
					$name = "--" + $o.long
					if ($usedOptions.Contains($name)) { continue }
					if ($o.short -and $usedOptions.Contains("-" + $o.short)) { continue }
					if ($name -like "$wordToComplete*") {
						$tooltip = $name
						if ($o.help) { $tooltip = $o.help }
						$results += [System.Management.Automation.CompletionResult]::new($name, $name, "ParameterName", $tooltip)
					}
				}
				return $results
			}

			# No full command match yet: complete the next verb.
			$candidates = New-Object System.Collections.Specialized.OrderedDictionary
			foreach ($c in $data.commands) {
				$verbSets = @()
				$verbSets += , @($c.verbs)
				foreach ($a in @($c.aliases)) { if ($null -ne $a) { $verbSets += , @($a) } }
				foreach ($set in $verbSets) {
					if ($set.Count -le $verbs.Count) { continue }
					$isMatch = $true
					for ($i = 0; $i -lt $verbs.Count; $i++) {
						if ($set[$i] -ne $verbs[$i]) { $isMatch = $false; break }
					}
					if (-not $isMatch) { continue }
					$next = $set[$verbs.Count]
					if (-not $candidates.Contains($next)) {
						$tooltip = $next
						if ($set.Count -eq $verbs.Count + 1 -and $c.help) { $tooltip = $c.help }
						$candidates[$next] = $tooltip
					}
				}
			}

			# Prefer the group help text for intermediate verbs, when available.
			foreach ($ns in @($data.namespaces)) {
				$nsVerbs = @($ns.verbs)
				if ($nsVerbs.Count -ne $verbs.Count + 1) { continue }
				$isMatch = $true
				for ($i = 0; $i -lt $verbs.Count; $i++) {
					if ($nsVerbs[$i] -ne $verbs[$i]) { $isMatch = $false; break }
				}
				if ($isMatch -and $ns.help -and $candidates.Contains($nsVerbs[$verbs.Count])) {
					$candidates[$nsVerbs[$verbs.Count]] = $ns.help
				}
			}

			foreach ($key in $candidates.Keys) {
				if ($key -like "$wordToComplete*") {
					$results += [System.Management.Automation.CompletionResult]::new($key, $key, "Command", $candidates[$key])
				}
			}
			return $results
		}
		""";
	}
}
