using Greg.Xrm.Command.Parsing;

namespace Greg.Xrm.Command.Commands.Data
{
	[Command("data", "init-schema-from-solution", HelpText = "Generate schema definition from an existing solution.")]
	public class DataInitSchemaCommand
	{
		[Option("solution", "s", Order = 1, Required = true, HelpText = "Solution unique name.")]
		public string SolutionUniqueName { get; set; } = "";

		[Option("output", "o", Order = 2, Required = true, HelpText = "Output file path for schema (YAML or JSON).")]
		public string OutputPath { get; set; } = "";

		[Option("format", "f", Order = 3, DefaultValue = "yaml", HelpText = "Output format: yaml, json.")]
		public string Format { get; set; } = "yaml";

		[Option("include", "i", Order = 4, HelpText = "Comma-separated list of entity logical names to include.")]
		public string[]? IncludeEntities { get; set; }

		[Option("exclude-relationships", Order = 5, HelpText = "Exclude relationship definitions from schema.")]
		public bool ExcludeRelationships { get; set; }

		[Option("exclude-optionsets", Order = 6, HelpText = "Exclude option set definitions from schema.")]
		public bool ExcludeOptionSets { get; set; }
	}

	[Command("data", "seed-mock", HelpText = "Generate mock/seed data for development environments from schema.")]
	public class DataSeedMockCommand
	{
		[Option("schema", "s", Order = 1, Required = true, HelpText = "Path to schema file (YAML or JSON) generated by init-schema-from-solution.")]
		public string SchemaPath { get; set; } = "";

		[Option("output", "o", Order = 2, Required = true, HelpText = "Output file path for mock data (ZIP compatible with data import).")]
		public string OutputPath { get; set; } = "";

		[Option("count", "c", Order = 3, DefaultValue = 100, HelpText = "Number of records to generate per entity.")]
		public int RecordCount { get; set; } = 100;

		[Option("strategy", Order = 4, DefaultValue = "random", HelpText = "Data generation strategy: random, sequential, fixed.")]
		public string Strategy { get; set; } = "random";

		[Option("seed", Order = 5, HelpText = "Random seed for reproducible data generation.")]
		public int? RandomSeed { get; set; }

		[Option("include-lookups", Order = 6, HelpText = "Generate lookup relationships between entities.")]
		public bool IncludeLookups { get; set; }
	}
}
