//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greg.Xrm.Command.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Greg.Xrm.Command.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4NLREgp6cRtYBv26AN8nLA==.
        /// </summary>
        internal static string AesIV {
            get {
                return ResourceManager.GetString("AesIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ptkJgAWEPctqlBQauyGg9VumFeG/j0Bwn/16X7AN6mQ=.
        /// </summary>
        internal static string AesKey {
            get {
                return ResourceManager.GetString("AesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Form {
        ///	formType = {
        ///		Create: 1,
        ///		Update: 2,
        ///		ReadOnly: 3,
        ///		Disabled: 4,
        ///		BulkEdit: 6
        ///	};
        ///
        ///	onLoad(executionContext) {
        ///		const formContext = executionContext.getFormContext();
        ///		const formType = formContext.ui.getFormType();
        ///	}
        ///}
        ///
        ///%NAMESPACE% = window.%NAMESPACE% || {};
        ///%NAMESPACE%.%TABLE% = %NAMESPACE%.%TABLE% || {};
        ///%NAMESPACE%.%TABLE%.Form = new Form();.
        /// </summary>
        internal static string TemplateJsForm {
            get {
                return ResourceManager.GetString("TemplateJsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Common {
        ///}
        ///
        ///%NAMESPACE% = window.%NAMESPACE% || {};
        ///%NAMESPACE%.Common = new Common();.
        /// </summary>
        internal static string TemplateJsOther {
            get {
                return ResourceManager.GetString("TemplateJsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Ribbon {
        ///}
        ///
        ///%NAMESPACE% = window.%NAMESPACE% || {};
        ///%NAMESPACE%.Global = %NAMESPACE%.Global || {};
        ///%NAMESPACE%.Global.Ribbon = new Ribbon();.
        /// </summary>
        internal static string TemplateJsRibbonGlobal {
            get {
                return ResourceManager.GetString("TemplateJsRibbonGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Ribbon {
        ///}
        ///
        ///%NAMESPACE% = window.%NAMESPACE% || {};
        ///%NAMESPACE%.%TABLE% = %NAMESPACE%.%TABLE% || {};
        ///%NAMESPACE%.%TABLE%.Ribbon = new Ribbon();.
        /// </summary>
        internal static string TemplateJsRibbonTable {
            get {
                return ResourceManager.GetString("TemplateJsRibbonTable", resourceCulture);
            }
        }
    }
}
